var annotated_dup =
[
    [ "Commands", "namespace_commands.html", [
      [ "AddLayerCmd", "class_commands_1_1_add_layer_cmd.html", "class_commands_1_1_add_layer_cmd" ],
      [ "AddShapeCmd", "class_commands_1_1_add_shape_cmd.html", "class_commands_1_1_add_shape_cmd" ],
      [ "BaseCmd", "class_commands_1_1_base_cmd.html", "class_commands_1_1_base_cmd" ],
      [ "JoinedCmd", "class_commands_1_1_joined_cmd.html", "class_commands_1_1_joined_cmd" ],
      [ "RemoveLayerCmd", "class_commands_1_1_remove_layer_cmd.html", "class_commands_1_1_remove_layer_cmd" ],
      [ "RemoveShapeCmd", "class_commands_1_1_remove_shape_cmd.html", "class_commands_1_1_remove_shape_cmd" ],
      [ "SelectCmd", "class_commands_1_1_select_cmd.html", "class_commands_1_1_select_cmd" ],
      [ "SetCmd", "class_commands_1_1_set_cmd.html", "class_commands_1_1_set_cmd" ],
      [ "SetRefCmd", "class_commands_1_1_set_ref_cmd.html", "class_commands_1_1_set_ref_cmd" ]
    ] ],
    [ "Controls", "namespace_controls.html", [
      [ "CanvasControl", "class_controls_1_1_canvas_control.html", "class_controls_1_1_canvas_control" ],
      [ "Grid", "class_controls_1_1_grid.html", "class_controls_1_1_grid" ],
      [ "Line", "class_controls_1_1_line.html", "class_controls_1_1_line" ],
      [ "Oval", "class_controls_1_1_oval.html", "class_controls_1_1_oval" ],
      [ "PathDraw", "class_controls_1_1_path_draw.html", "class_controls_1_1_path_draw" ],
      [ "PathEdit", "class_controls_1_1_path_edit.html", "class_controls_1_1_path_edit" ],
      [ "Polygon", "class_controls_1_1_polygon.html", "class_controls_1_1_polygon" ],
      [ "Rect", "class_controls_1_1_rect.html", "class_controls_1_1_rect" ],
      [ "Ruler", "class_controls_1_1_ruler.html", "class_controls_1_1_ruler" ],
      [ "Select", "class_controls_1_1_select.html", "class_controls_1_1_select" ],
      [ "Text", "class_controls_1_1_text.html", "class_controls_1_1_text" ],
      [ "Transform", "class_controls_1_1_transform.html", "class_controls_1_1_transform" ]
    ] ],
    [ "Parser", "namespace_parser.html", [
      [ "BaseContext", "class_parser_1_1_base_context.html", "class_parser_1_1_base_context" ],
      [ "ChildContextFactories", "struct_parser_1_1_child_context_factories.html", null ],
      [ "ColorFactoryBase", "struct_parser_1_1_color_factory_base.html", "struct_parser_1_1_color_factory_base" ],
      [ "CSSContext", "class_parser_1_1_c_s_s_context.html", "class_parser_1_1_c_s_s_context" ],
      [ "GroupContext", "class_parser_1_1_group_context.html", "class_parser_1_1_group_context" ],
      [ "ImageContext", "class_parser_1_1_image_context.html", "class_parser_1_1_image_context" ],
      [ "InheritedStyle", "struct_parser_1_1_inherited_style.html", "struct_parser_1_1_inherited_style" ],
      [ "ObjectContext", "class_parser_1_1_object_context.html", "class_parser_1_1_object_context" ],
      [ "PaintContext", "class_parser_1_1_paint_context.html", "class_parser_1_1_paint_context" ],
      [ "ReferencedSymbolOrSvgContext", "class_parser_1_1_referenced_symbol_or_svg_context.html", "class_parser_1_1_referenced_symbol_or_svg_context" ],
      [ "ShapeContext", "class_parser_1_1_shape_context.html", "class_parser_1_1_shape_context" ],
      [ "StylableContext", "class_parser_1_1_stylable_context.html", "class_parser_1_1_stylable_context" ],
      [ "Style", "struct_parser_1_1_style.html", "struct_parser_1_1_style" ],
      [ "SVGPPDoc", "class_parser_1_1_s_v_g_p_p_doc.html", "class_parser_1_1_s_v_g_p_p_doc" ],
      [ "SVGPPParser", "class_parser_1_1_s_v_g_p_p_parser.html", "class_parser_1_1_s_v_g_p_p_parser" ],
      [ "TextContext", "class_parser_1_1_text_context.html", "class_parser_1_1_text_context" ],
      [ "TransformableContext", "class_parser_1_1_transformable_context.html", "class_parser_1_1_transformable_context" ],
      [ "UseContext", "class_parser_1_1_use_context.html", "class_parser_1_1_use_context" ]
    ] ],
    [ "BaseContainer", "class_base_container.html", "class_base_container" ],
    [ "BaseGenerator", "class_base_generator.html", "class_base_generator" ],
    [ "BaseJob", "class_base_job.html", "class_base_job" ],
    [ "BitmapShape", "class_bitmap_shape.html", "class_bitmap_shape" ],
    [ "CacheStack", "class_cache_stack.html", "class_cache_stack" ],
    [ "Canvas", "class_canvas.html", "class_canvas" ],
    [ "CanvasTextEdit", "class_canvas_text_edit.html", "class_canvas_text_edit" ],
    [ "Clipboard", "class_clipboard.html", "class_clipboard" ],
    [ "CollapseButton", "class_collapse_button.html", "class_collapse_button" ],
    [ "DocPanel", "class_doc_panel.html", "class_doc_panel" ],
    [ "Document", "class_document.html", "class_document" ],
    [ "DocumentSerializer", "class_document_serializer.html", "class_document_serializer" ],
    [ "DocumentSettings", "class_document_settings.html", "class_document_settings" ],
    [ "FCodeGenerator", "class_f_code_generator.html", "class_f_code_generator" ],
    [ "FontPanel", "class_font_panel.html", "class_font_panel" ],
    [ "GCodeGenerator", "class_g_code_generator.html", "class_g_code_generator" ],
    [ "GCodePlayer", "class_g_code_player.html", "class_g_code_player" ],
    [ "GroupShape", "class_group_shape.html", "class_group_shape" ],
    [ "Layer", "class_layer.html", "class_layer" ],
    [ "LayerListItem", "class_layer_list_item.html", "class_layer_list_item" ],
    [ "LayerPanel", "class_layer_panel.html", "class_layer_panel" ],
    [ "LayerParamsPanel", "class_layer_params_panel.html", "class_layer_params_panel" ],
    [ "MachineManager", "class_machine_manager.html", "class_machine_manager" ],
    [ "MachineMonitor", "class_machine_monitor.html", "class_machine_monitor" ],
    [ "MachineSettings", "class_machine_settings.html", "class_machine_settings" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "NewMachineDialog", "class_new_machine_dialog.html", "class_new_machine_dialog" ],
    [ "PathShape", "class_path_shape.html", "class_path_shape" ],
    [ "PreferencesWindow", "class_preferences_window.html", "class_preferences_window" ],
    [ "PresetManager", "class_preset_manager.html", "class_preset_manager" ],
    [ "PresetSettings", "class_preset_settings.html", "class_preset_settings" ],
    [ "PreviewGenerator", "class_preview_generator.html", "class_preview_generator" ],
    [ "PreviewWindow", "class_preview_window.html", "class_preview_window" ],
    [ "QDoubleSpinBox2", "class_q_double_spin_box2.html", "class_q_double_spin_box2" ],
    [ "SerialJob", "class_serial_job.html", "class_serial_job" ],
    [ "Shape", "class_shape.html", "class_shape" ],
    [ "SpoolerPanel", "class_spooler_panel.html", "class_spooler_panel" ],
    [ "SVGNode", "class_s_v_g_node.html", "class_s_v_g_node" ],
    [ "SVGStyleSelector", "class_s_v_g_style_selector.html", "class_s_v_g_style_selector" ],
    [ "TaskListItem", "class_task_list_item.html", "class_task_list_item" ],
    [ "TextShape", "class_text_shape.html", "class_text_shape" ],
    [ "ToolpathExporter", "class_toolpath_exporter.html", "class_toolpath_exporter" ],
    [ "TransformPanel", "class_transform_panel.html", "class_transform_panel" ],
    [ "WelcomeDialog", "class_welcome_dialog.html", "class_welcome_dialog" ]
];